# Generated by Django 4.2.17 on 2025-01-06 10:18

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('review_text', models.TextField()),
                ('release_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.commonreviewdata')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='TVReview',
            fields=[
                ('commonreviewdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.commonreviewdata')),
                ('number_of_episodes', models.IntegerField()),
                ('showrunner', models.CharField(max_length=100)),
                ('average_episode_length', models.DurationField()),
                ('category', models.ForeignKey(default=review.models.Category.tv_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.category')),
            ],
            bases=('review.commonreviewdata',),
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('commonreviewdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.commonreviewdata')),
                ('runtime', models.DurationField()),
                ('director', models.CharField(max_length=100)),
                ('category', models.ForeignKey(default=review.models.Category.film_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.category')),
            ],
            bases=('review.commonreviewdata',),
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('commonreviewdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.commonreviewdata')),
                ('studio', models.CharField(max_length=100)),
                ('time_to_beat', models.DurationField()),
                ('number_of_players', models.IntegerField()),
                ('category', models.ForeignKey(default=review.models.Category.game_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.category')),
            ],
            bases=('review.commonreviewdata',),
        ),
    ]
